/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "3d-book": {
    name: "3d-book",
    description: "یک کتاب سه‌بعدی تعاملی با انیمیشن ورق‌زدن صفحات.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/3d-book.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/3d-book.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "3d-book"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accessible-action": {
    name: "accessible-action",
    description: "پشتهٔ کارت قابل کشیدن با شیب سه‌بعدی، ژست ارسال به پشت، کلیک، چرخش تصادفی و فنر نرم.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/accessible-action.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/accessible-action-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "accessible-action"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordionos": {
    name: "accordionos",
    description: "آکاردئون شماره‌دار که با باز شدن هر ردیف تصویر بزرگ را عوض می‌کند، با پخش خودکار اختیاری.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/accordionos.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/accordionos.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "accordionos"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "analog-stick": {
    name: "analog-stick",
    description: "اهرم فلزی که با فشار کج می‌شود. روی یک ربع هاور کنید؛ کلاهک می‌لرزد، سایه جابه‌جا می‌شود و فلش همرنگ کهربایی می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/analog-stick.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/analog-stick-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "analog-stick"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-bar-chart": {
    name: "animated-bar-chart",
    description: "نمودار میله‌ای با رشد فنری، هاور و پخش دوباره — فقط SVG و Motion.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/animated-bar-chart.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/animated-bar-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-line-chart": {
    name: "animated-line-chart",
    description: "نمودار خطی ناحیه‌دار با راهنمای هاور، کارت جزئیات و درصد تغییر — فقط SVG و Motion.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/animated-line-chart.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/animated-line-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-line-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-donut-chart": {
    name: "animated-donut-chart",
    description: "دونات سهم‌بندی با رسم پله‌ای، هاور و فهرست کنار — فقط SVG و Motion.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/animated-donut-chart.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/animated-donut-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-donut-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-spark-chart": {
    name: "animated-spark-chart",
    description: "کارت متریک فشرده با عدد، درصد تغییر و اسپارک‌لاین متحرک — فقط SVG و Motion.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/animated-spark-chart.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/animated-spark-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-spark-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "command-palette": {
    name: "command-palette",
    description: "جست‌وجو و اجرای سریع دستورات با کیبورد — پالت فرمان RTL با گروه‌ها و شورتکات.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/command-palette.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/command-palette-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "command-palette"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "kanban-board": {
    name: "kanban-board",
    description: "برد مدیریت تسک با جابه‌جایی کارت‌ها بین ستون‌ها — درگ‌اند‌دراپ با Motion.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/kanban-board.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/kanban-board-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "kanban-board"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-collection": {
    name: "animated-collection",
    description: "مجموعه‌ای از آثار که بین نمای فهرست، کارت و پشتهٔ فشرده مورف می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/animated-collection.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/animated-collection.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-collection"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animate-tabs": {
    name: "animate-tabs",
    description: "تب‌های لایه‌ای با هایلایت فنری و پنل‌های ارتفاع‌متغیر — از Animate UI.",
    type: "registry:component",
    registryDependencies: ["button","card","input","label"],
    files: [{
      path: "registry/default/example/animate-tabs.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/animate-tabs-core.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/animate-tabs-highlight.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/animate-tabs-slot.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/animate-tabs-context.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/animate-tabs.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animate-tabs"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-tabs": {
    name: "animated-tabs",
    description: "تب متحرک با زبان بصری فیلتر — Estedad، bg-card، border-border و نشانگر accent.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/animated-tabs.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/animated-tabs-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-tabs"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bento-card": {
    name: "bento-card",
    description: "یک کاشی شیشه‌ای با تب‌هایی که پیش‌نمای داشبورد را داخل همان کارت عوض می‌کنند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/bento-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/bento-card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "bento-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bloom-menu": {
    name: "bloom-menu",
    description: "دکمه‌ای که به منو تبدیل می‌شود و از مرکز مثل عنبیه، با آیتم‌های پله‌ای شعاعی باز می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/bloom-menu.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/bloom-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "bloom-menu"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bounce-cards": {
    name: "bounce-cards",
    description: "بادبزن کارت‌های عکسی که با بانس وارد می‌شوند؛ با هاور از هم باز می‌شوند و کارت فعال صاف می‌ایستد.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/bounce-cards.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/bounce-cards-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "bounce-cards"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bottom-menu": {
    name: "bottom-menu",
    description: "داک فشرده‌ای که به جستجو، یادداشت، اعلان، پروفایل و تم باز می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/bottom-menu.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/bottom-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "bottom-menu"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bucket": {
    name: "bucket",
    description: "قیف شیشه‌ای که چیپ‌های قابلیت را یکی‌یکی مثل سینی گیراندازی پرتاب می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/bucket.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "hooks/use-mobile.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/bucket-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "bucket"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-folder": {
    name: "card-folder",
    description: "کارت پوشه‌ای متحرک با تصویر پس‌زمینه، شیء شناور، افکت هاور و رنگ و متن قابل تنظیم.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/card-folder.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/card-folder-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "card-folder"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "client-card": {
    name: "client-card",
    description: "کارت CRM مشتری با حلقه‌های پرداخت و مهلت، به‌علاوهٔ پشتهٔ آواتار مورف‌شونده.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/client-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/client-card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "client-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "comet-dial": {
    name: "comet-dial",
    description: "صفحهٔ حلقه‌ای که با زاویه می‌کشی؛ دنبالهٔ دنباله‌دار پشت سرِ نوک روشن می‌آید.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/comet-dial.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/comet-dial-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "comet-dial"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "confidential-folder": {
    name: "confidential-folder",
    description: "غلاف زغالی که نامه را بیرون می‌کشد، برمی‌گرداند و روبه‌روی شما می‌نشاند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/confidential-folder.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/confidential-folder.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "confidential-folder"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "corner-video": {
    name: "corner-video",
    description: "پخش‌کنندهٔ جمع‌وجور گوشه با مورف باز/بسته، پخش خودکار، بی‌صدا، بزرگ‌نمایی، کنترل هاور و اسکراب ویدیو.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/corner-video.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/corner-video-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "corner-video"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "coverflow-drag": {
    name: "coverflow-drag",
    description: "کاورفلوی افقی از پرتره‌ها که با کشیدن کوچک، کم‌نور و قفل می‌شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/coverflow-drag.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/coverflow-drag-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "coverflow-drag"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "create-menu": {
    name: "create-menu",
    description: "قرص «شروع ساخت» که با فنر به فهرست اکشن‌های ساخت باز می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/create-menu.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/create-menu-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "create-menu"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "curve-drawer": {
    name: "curve-drawer",
    description: "کشوهای کناری که لبهٔ داخلی‌شان با برآمدگی شروع می‌شود و با نشستن پنل صاف می‌شود.",
    type: "registry:component",
    registryDependencies: ["button"],
    files: [{
      path: "registry/default/example/curve-drawer.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/curve-drawer-primitives.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/curve-drawer-curve.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/curve-drawer-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "curve-drawer"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "date-field": {
    name: "date-field",
    description: "فیلد انتخاب تاریخ شمسی که با کلیک به تقویم مورف می‌شود؛ ماه و سال جداگانه عوض می‌شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/date-field.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/date-field-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "date-field"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "jalali-wheel-picker": {
    name: "jalali-wheel-picker",
    description: "چرخان انتخاب تاریخ و ساعت شمسی به سبک آیفون.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/jalali-wheel-picker.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/jalali-wheel-picker-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "jalali-wheel-picker"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "peek-rating": {
    name: "peek-rating",
    description: "امتیاز ستاره‌ای با پیش‌نمایش موج‌دار قبل از ثبت.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/peek-rating.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/peek-rating-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "peek-rating"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pulse-heart": {
    name: "pulse-heart",
    description: "دکمه پسند با جمع‌شدن به نقطه، تعویض رنگ و پالس برگشت.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/pulse-heart.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/pulse-heart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "pulse-heart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "number-ticker": {
    name: "number-ticker",
    description: "شمارنده عددی با اسپرینگ نرم تا مقدار هدف؛ ارقام فارسی.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/number-ticker.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/number-ticker-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "number-ticker"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "voice-orb": {
    name: "voice-orb",
    description: "کرهٔ مایع تنفس‌کننده برای تجسم صدا با WebGL.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/voice-orb.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/voice-orb-renderer.ts",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/voice-orb-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "voice-orb"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "team-carousel": {
    name: "team-carousel",
    description: "کاروسل سه‌بعدی اعضای تیم با ناوبری لمسی و کیبورد.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/team-carousel.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/team-carousel-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "team-carousel"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "approval-card": {
    name: "approval-card",
    description: "کارت تصمیم انسان‌درحلقه برای تأیید، پرسش چندمرحله‌ای و ثبت نتیجه.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/approval-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/approval-card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "approval-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "image-generation": {
    name: "image-generation",
    description: "سطح پایدار تصویر تولیدشده از صف تا نتیجه، بدون پرش چیدمان.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/image-generation.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/image-generation-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "image-generation"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "morphing-tabs": {
    name: "morphing-tabs",
    description: "تب‌های قابل‌جابه‌جایی با سطح مایع که به محتوای فعال وصل می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/morphing-tabs.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/morphing-tabs-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "morphing-tabs"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "signup-form": {
    name: "signup-form",
    description: "فرم ثبت‌نام با خطای پس از ترک فیلد، متر قدرت رمز و چرخهٔ ارسال.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/signup-form.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/signup-form-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "signup-form"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "day-picker": {
    name: "day-picker",
    description: "چیپ تکرار که به روزانه / هفتگی / ماهانه / سالانه باز می‌شود، بعد به روزهای هفته.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/day-picker.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/day-picker.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "day-picker"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "delete-button": {
    name: "delete-button",
    description: "دکمهٔ قرمز حذف که قبل از انجام کار به شمارش معکوس با امکان لغو تبدیل می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/delete-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/delete-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "delete-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dial-volume": {
    name: "dial-volume",
    description: "ولوم فلزی را بچرخان؛ حلقهٔ چراغ‌های مربعی سطح صدا را نشان می‌دهد و درصد به‌روز می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/dial-volume.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/dial-volume-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "dial-volume"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "discover-button": {
    name: "discover-button",
    description: "کنترل گرد جستجو که کنار تراشه‌های محبوب و علاقه‌مندی‌ها به فیلد کشیده می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/discover-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/discover-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "discover-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "discrete-tabs": {
    name: "discrete-tabs",
    description: "تب‌های آیکنی فشرده با زبان بصری فیلتر — Estedad، bg-card و باز شدن برچسب روی فعال.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/discrete-tabs.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/discrete-tabs-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "discrete-tabs"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "drawer-buttons": {
    name: "drawer-buttons",
    description: "دو دکمه که کشوی کناری را با تا شدن سه‌بعدی باز می‌کنند. پرداخت از راست، سبد از چپ؛ فیلدها پشت‌سرهم ظاهر می‌شوند.",
    type: "registry:component",
    registryDependencies: ["button","input","textarea","select","field"],
    files: [{
      path: "registry/default/example/drawer-buttons.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/drawer-buttons-drawer.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/drawer-buttons-field.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/drawer-buttons-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "drawer-buttons"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dynamic-grid-gallery": {
    name: "dynamic-grid-gallery",
    description: "گرید عکسی ۳×۲ که ردیف و ستون هاور‌شده را بزرگ می‌کند تا یک قاب مرکز صحنه شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/dynamic-grid-gallery.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/dynamic-grid-gallery-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "dynamic-grid-gallery"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dynamic-toolbar": {
    name: "dynamic-toolbar",
    description: "نوار آیکنی که با ورق زدن بین ابزارهای اصلی و مجموعهٔ دوم، عرضش را عوض می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/dynamic-toolbar.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "hooks/use-measure.tsx",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/dynamic-toolbar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "dynamic-toolbar"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "editorial-deck": {
    name: "editorial-deck",
    description: "دستهٔ داستان تحریریه‌ای روی هم. کارت جلو را بکشید؛ با فنر به ته دسته برمی‌گردد.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/editorial-deck.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/editorial-deck-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "editorial-deck"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "empty-testimonial": {
    name: "empty-testimonial",
    description: "حالت خالی «دیوار محبت» — روی پوشه بزنید؛ سه برگه با فنر بیرون می‌آیند تا اولین نقل‌قول را اضافه کنید.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/empty-testimonial.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/empty-testimonial-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "empty-testimonial"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "event-countdown": {
    name: "event-countdown",
    description: "نشان می‌دهد چقدر تا شروع رویداد مانده — روز، ساعت، دقیقه و ثانیه.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/event-countdown.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/event-countdown-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "event-countdown"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "expandable-action-bar": {
    name: "expandable-action-bar",
    description: "اکشن‌های آیکونی فشرده که با هاور یا فوکوس به کنترل‌های برچسب‌دار باز می‌شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/expandable-action-bar.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/expandable-action-bar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "expandable-action-bar"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "expandable-gallery": {
    name: "expandable-gallery",
    description: "گالری عکس با باز شدن نرم آیتم‌ها از پشته به شبکه.",
    type: "registry:component",
    registryDependencies: ["button"],
    files: [{
      path: "registry/default/example/expandable-gallery.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/expandable-gallery-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "expandable-gallery"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "feature-carousel": {
    name: "feature-carousel",
    description: "چیپ‌های شناور یک‌طرف، عکس بزرگ طرف دیگر — قابلیت را بزن، تصویر دنبال می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/feature-carousel.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/feature-carousel-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "feature-carousel"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "file-upload-progress": {
    name: "file-upload-progress",
    description: "نمایش پیشرفت آپلود فایل‌ها با وضعیت موفقیت و خطا.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/file-upload-progress.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/file-upload-progress-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "file-upload-progress"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "filter-interaction": {
    name: "filter-interaction",
    description: "فهرست فیلتر تعاملی با هاور، انتخاب و پنل تغییرشکل‌دهنده.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/filter-interaction.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/filter-interaction.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "filter-interaction"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "fluid-expanding-grid": {
    name: "fluid-expanding-grid",
    description: "شبکهٔ عکسی که با کلیک یکی ردیف را می‌گیرد و بقیه کنار می‌روند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/fluid-expanding-grid.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/fluid-expanding-grid.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "fluid-expanding-grid"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "focus-testimonials": {
    name: "focus-testimonials",
    description: "ردیف آواتار — روی یکی هاور کن تا نقل‌قول جلو بیاید و تولتیپ نام دنبال ماوس برود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/focus-testimonials.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/focus-testimonials.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "focus-testimonials"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "folder-interaction": {
    name: "folder-interaction",
    description: "پوشه‌ای که با کلیک باز می‌شود و برگه‌ها با فنر بیرون می‌آیند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/folder-interaction.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/folder-interaction.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "folder-interaction"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "get-in-touch": {
    name: "get-in-touch",
    description: "قرص براق تماس. هاور کنید تا برچسب برود، پرتره و «شما» یکی شوند، بعد «بزن حرف بزنیم!» نوشته شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/get-in-touch.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/get-in-touch-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/get-in-touch-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "get-in-touch"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "glide-select": {
    name: "glide-select",
    description: "چیپ انتخاب که منویش از گوشه باز می‌شود و هایلایت بین ردیف‌ها می‌لغزد.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/glide-select.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/glide-select-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "glide-select"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "holographic-referral-card": {
    name: "holographic-referral-card",
    description: "کارت دعوت تیره که با اشاره‌گر سه‌بعدی کج می‌شود؛ درخشش هولوگرافیک دنبال می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/holographic-referral-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/holographic-referral-card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "holographic-referral-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "gooey-navbar": {
    name: "gooey-navbar",
    description: "ناوبری قرصی که با هاور به همسایه ذوب می‌شود — پل مایع و نقطهٔ فعال.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/gooey-navbar.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/gooey-navbar-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "gooey-navbar"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "infinite-grid": {
    name: "infinite-grid",
    description: "بوم محصول با حرکت آزاد که تا ابد کاشی می‌شود — بکشید، اسکرول کنید، ورق بزنید.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/infinite-grid.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/infinite-grid.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "infinite-grid"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "infinite-masonry": {
    name: "infinite-masonry",
    description: "میسونری مجازی واکنش‌گرا با ارتفاع متغیر کارت‌ها و بارگذاری بیشتر هنگام نزدیک‌شدن به انتها.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/infinite-masonry.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/infinite-masonry.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "infinite-masonry"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "inline-edit": {
    name: "inline-edit",
    description: "ورودی که بین حالت خواندن و ویرایش جابه‌جا می‌شود.",
    type: "registry:component",
    registryDependencies: ["input"],
    files: [{
      path: "registry/default/example/inline-edit.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/inline-edit.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "inline-edit"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "lanyard": {
    name: "lanyard",
    description: "بج سه‌بعدی آویزان روی بند کشسان؛ قابل کشیدن، پرتاب و برگرداندن با کلیک.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/lanyard.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/lanyard-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "lanyard"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "lanyard-badge": {
    name: "lanyard-badge",
    description: "بج سه‌بعدی با فیزیک بند Verlet؛ بکشید، بچرخانید یا پشت کارت را ببینید. بدون وابستگی.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/lanyard-badge.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/lanyard-badge-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "lanyard-badge"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "liquid-index": {
    name: "liquid-index",
    description: "فهرست قابلیتی که نشان هاور آن گرادیان مایع WebGL است و ردیف را دنبال می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/liquid-index.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/liquid-index-canvas.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/liquid-index-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "liquid-index"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "loading-states": {
    name: "loading-states",
    description: "سه حالت بارگذاری برای رابط ایجنت: متن درخشان، پیشرفت زنده، و عبارات استدلال چرخشی.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/loading-states.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/loading-states.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "loading-states"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "luck-wheel": {
    name: "luck-wheel",
    description: "چرخ شانس کازینویی؛ سرعت را انتخاب کن، بچرخان، با شتاب و ترمز نرم روی جایزه می‌ایستد.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/luck-wheel.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/luck-wheel-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "luck-wheel"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "magnified-bento": {
    name: "magnified-bento",
    description: "کارت بنتو با لنز ذره‌بین قابل‌کشیدن روی چیپ‌های در حال اسکرول.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/magnified-bento.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/magnified-bento-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "magnified-bento"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "morphing-input": {
    name: "morphing-input",
    description: "فیلد ورودی که بین حالت‌های مختلف شکل عوض می‌کند.",
    type: "registry:component",
    registryDependencies: ["input"],
    files: [{
      path: "registry/default/example/morphing-input.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/morphing-input.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "morphing-input"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "nested-dropdown": {
    name: "nested-dropdown",
    description: "منوی تو‌در‌تو با زبان بصری فیلتر — دایره ۸۰، پنل card، ردیف text-xl؛ فقط بازشونده.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/nested-dropdown.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/nested-dropdown-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "nested-dropdown"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "toast-stack": {
    name: "toast-stack",
    description: "اعلان‌های موفقیت، خطا و هشدار با ورود و خروج انیمیشنی و پشتهٔ فنری.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/toast-stack.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/toast-stack-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "toast-stack"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "todo-list": {
    name: "todo-list",
    description: "برنامهٔ وظایف ایجنت با وضعیت‌های متحرک، شمارندهٔ پیشرفت و جمع‌شدن نرم.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/todo-list.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/todo-list.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "todo-list"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "tooltip": {
    name: "tooltip",
    description: "تولتیپ نرم روی دکمه‌های گرد — سطح card، شعاع ۱۶ و فنر کوتاه.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/tooltip.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/tooltip.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "tooltip"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "undo-delete": {
    name: "undo-delete",
    description: "حذف آیتم از فهرست با نوار بازگردانی و شمارش معکوس.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/undo-delete.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/undo-delete-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "undo-delete"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "upload-dropzone": {
    name: "upload-dropzone",
    description: "درگ فایل → مورف پیش‌نمایش + نوار پیشرفت فیزیکی؛ آپلود محصول و مدارک.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/upload-dropzone.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/upload-dropzone-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "upload-dropzone"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "typed-code": {
    name: "typed-code",
    description: "دکمهٔ نمایش کد → کارت VS Code Dark+؛ تایپ نرم کاراکتر‌به‌کاراکتر.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/typed-code.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/typed-code-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "typed-code"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-switches": {
    name: "animated-switches",
    description: "سوئیچ‌های انیمیشنی نرم، آیکنی و مایع — سبز آیفون، انگشتک فنری یک‌اندازه.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/animated-switches.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/animated-switches-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-switches"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-checkboxes": {
    name: "animated-checkboxes",
    description: "چک‌باکس‌های انیمیشنی نرم، دایره‌ای و جهشی — سبز آیفون، تیک رسم‌شونده.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/animated-checkboxes.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/animated-checkboxes-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-checkboxes"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-select": {
    name: "animated-select",
    description: "سلکت انیمیشنی — تریگر نرم، لیست فنری، هایلایت لغزان و تیک سبز.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/animated-select.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/animated-select-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-select"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sortable-list": {
    name: "sortable-list",
    description: "لیست قابل مرتب‌سازی با Drag & Drop — دستهٔ درگ، فنر، شمارهٔ اولویت.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/sortable-list.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/sortable-list-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "sortable-list"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-data-table": {
    name: "animated-data-table",
    description: "جدول داده با فیلتر، مرتب‌سازی ستون و جابه‌جایی ردیف با انیمیشن روان.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/animated-data-table.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/animated-data-table-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-data-table"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-sidebars": {
    name: "animated-sidebars",
    description: "سایدبار ریل جمع‌شونده با زیرمنوی درختی و تم فیلتر تعاملی.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/animated-sidebars.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/animated-sidebars-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-sidebars"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "horizontal-menu": {
    name: "horizontal-menu",
    description: "منوی افقی با زیرمنوی هاور و پنل کناری تودرتو.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/horizontal-menu.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/horizontal-menu-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "horizontal-menu"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "expandable-card": {
    name: "expandable-card",
    description: "کارت کوچک → نمای بزرگ با layout مشترک و جزئیات فنری.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/expandable-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/expandable-card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "expandable-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "multi-step-form": {
    name: "multi-step-form",
    description: "فرم چندمرحله‌ای پویا و متحرک با اعتبارسنجی.",
    type: "registry:component",
    registryDependencies: ["card","button","input","textarea","select","badge","calendar","popover"],
    files: [{
      path: "registry/default/example/multi-step-form.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/multi-step-form.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "multi-step-form"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "overlapping-slider": {
    name: "overlapping-slider",
    description: "ردیف تمام‌عرض کارت‌های پرتره؛ با حرکت، کارت قبلی کوچک و عقب می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/overlapping-slider.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/overlapping-slider-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "overlapping-slider"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "otp-cascade": {
    name: "otp-cascade",
    description: "شش خانهٔ کد تأیید؛ رقم‌ها یکی‌یکی پر می‌شوند و با کد درست یا غلط بازخورد سبز یا قرمز می‌گیری.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/otp-cascade.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/otp-cascade-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "otp-cascade"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "perspective-text-scroll": {
    name: "perspective-text-scroll",
    description: "متنی که با اسکرول در پرسپکتیو می‌آید، می‌نشیند و دور می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/perspective-text-scroll.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/perspective-text-scroll-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "perspective-text-scroll"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "photo-albums": {
    name: "photo-albums",
    description: "پشته‌های کج آلبوم که به شبکهٔ عکس با المان مشترک باز می‌شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/photo-albums.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/photo-albums-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "photo-albums"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "paper-shred-button": {
    name: "paper-shred-button",
    description: "روی حذف هاور کنید تا صفحه ظاهر شود. کلیک کنید تا صفحه بریده شود و نوارهای کاغذ پایین کشیده شوند. بعد از چند ثانیه ریست می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/paper-shred-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/paper-shred-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "paper-shred-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "polaroid-drag": {
    name: "polaroid-drag",
    description: "چاپ‌های فوری که روی میز می‌کشید — با سرعت کج می‌شوند، روی هم می‌آیند و نوار چسب یا پونز می‌گیرند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/polaroid-drag.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/polaroid-drag-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "polaroid-drag"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "polaroid-stack": {
    name: "polaroid-stack",
    description: "هفت پولاروید روی هم. با هاور به قوسی از یک گوشه بادبزن می‌شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/polaroid-stack.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/polaroid-stack-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "polaroid-stack"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pop-tilt-cards": {
    name: "pop-tilt-cards",
    description: "دستهٔ پاستلی بادبزنی — روی یک کارت هاور کنید تا بالا بپرد و همسایه‌ها کج شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/pop-tilt-cards.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/pop-tilt-cards-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "pop-tilt-cards"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pricing-card": {
    name: "pricing-card",
    description: "انتخابگر باریک پلن با سوییچ ماهانه/سالانه، قیمت‌های غلتان و برچسب تخفیف.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/pricing-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/pricing-card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "pricing-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "prize-coins": {
    name: "prize-coins",
    description: "جعبه طلایی جایزه را باز کن؛ سکه‌ها پرواز می‌کنند و در شمارندهٔ گوشه جمع می‌شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/prize-coins.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/prize-coins-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "prize-coins"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "profile-card": {
    name: "profile-card",
    description: "کارت پروفایل قاب‌دار که با نشانگر کج می‌شود و فویل هولوگرافیک از الگوی کاشی می‌درخشد.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/profile-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/profile-card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "profile-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "prompt-box": {
    name: "prompt-box",
    description: "کامپوزر چت جمع‌شده که به textarea با منوی مدل، کنترل ارسال و پیش‌نمایش هاور مدل انتخاب‌شده باز می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/prompt-box.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/prompt-box-icons.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/prompt-box-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "prompt-box"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "rolling-card-stack": {
    name: "rolling-card-stack",
    description: "پشتهٔ کارت غلتان واکنش‌گرا با سوایپ، کیبورد، پخش خودکار و محتوای قابل تنظیم.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/rolling-card-stack.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/rolling-card-stack.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "rolling-card-stack"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "save-button": {
    name: "save-button",
    description: "دکمه‌ای با وضعیت‌های متحرک برای آماده، در حال ذخیره و موفق.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/save-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/save-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "save-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scan-document": {
    name: "scan-document",
    description: "روی اسکن بزن؛ صفحه باز می‌شود، می‌چرخد و نوار نور آن را می‌خواند. بعد از انجام‌شدن ریست می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/scan-document.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/scan-document-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "scan-document"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scroll-split-cards": {
    name: "scroll-split-cards",
    description: "یک عکس که با اسکرول به سه پنل می‌شکند، بعد برمی‌گردد و متن نشان می‌دهد.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/scroll-split-cards.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/scroll-split-cards-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "scroll-split-cards"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scroll-stack-deck": {
    name: "scroll-stack-deck",
    description: "کارت‌های پروژهٔ وابسته به اسکرول که در ویوپورت پین می‌شوند و با پایین‌آمدن پشته، مقیاس و نشست پیدا می‌کنند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/scroll-stack-deck.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/scroll-stack-deck-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "scroll-stack-deck"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "set-timer": {
    name: "set-timer",
    description: "چرخ را بچرخان، شروع کن، بعد مکث یا لغو. یک سطح در هر مرحله شکل عوض می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/set-timer.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/set-timer-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "set-timer"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shake-testimonial-card": {
    name: "shake-testimonial-card",
    description: "کارت‌های نظر که می‌لرزند و بعد به پشت پشته پرتاب می‌شوند — پخش خودکار یا کلیک.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/shake-testimonial-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/shake-testimonial-card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "shake-testimonial-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "slosh-gauge": {
    name: "slosh-gauge",
    description: "گیج مخزن که مایع مقدار را تعقیب می‌کند، هنگام حرکت کج می‌شود و موقع پر شدن می‌پاشد.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/slosh-gauge.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/slosh-gauge-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "slosh-gauge"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "slide-subscribe": {
    name: "slide-subscribe",
    description: "دورهٔ صورتحساب را انتخاب کنید، بعد برای شروع آزمایش بکشید.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/slide-subscribe.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/slide-subscribe-unlock.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/slide-subscribe-shimmer.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/slide-subscribe-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "slide-subscribe"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "smooth-dropdown": {
    name: "smooth-dropdown",
    description: "دکمهٔ گردی که به منو تبدیل می‌شود — ردیف‌ها پلکانی می‌آیند، پوسته تغییر اندازه می‌دهد و با کلیک بیرون بسته می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/smooth-dropdown.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/smooth-dropdown.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "smooth-dropdown"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "spotlight-card": {
    name: "spotlight-card",
    description: "کارت با نورافکن نرم که اشاره‌گر را دنبال می‌کند، لبه را روشن می‌کند و به کارت‌های نزدیک می‌رسد.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/spotlight-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/spotlight-card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "spotlight-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "stack-scroll-reveal": {
    name: "stack-scroll-reveal",
    description: "کارت‌های مطالعهٔ موردی وابسته به اسکرول که در ویوپورت پین می‌شوند و با پایین آمدن ورق می‌خورند، کوچک می‌شوند و محو می‌شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/stack-scroll-reveal.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/stack-scroll-reveal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "stack-scroll-reveal"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "stacked-list": {
    name: "stacked-list",
    description: "ویجت افراد — پشتهٔ کوتاه اعضا که به فهرست قابل جستجو تبدیل می‌شود.",
    type: "registry:component",
    registryDependencies: ["input","button"],
    files: [{
      path: "registry/default/example/stacked-list.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/stacked-list.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "stacked-list"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "stacked-outline-text": {
    name: "stacked-outline-text",
    description: "تایپ خط‌دار سنگین که می‌توانید بکشید. سرعت، رد سفید-روی-سیاه پشته‌ای می‌گذارد که با رها کردن برمی‌گردد.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/stacked-outline-text.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/stacked-outline-text-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "stacked-outline-text"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "stamp-approve": {
    name: "stamp-approve",
    description: "روی مهر تأیید بزن؛ مهر باد می‌گیرد، روی سند می‌خورد و اثر دایره‌ای «تأیید شد» دقیقاً همان‌جا می‌ماند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/stamp-approve.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/stamp-approve-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "stamp-approve"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "status-mark": {
    name: "status-mark",
    description: "نشان وضعیت وظیفهٔ ایجنت — از حلقهٔ بیکار به کمان پیشرفت، بعد تیک یا ضربدر.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/status-mark.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/status-mark-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "status-mark"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "swipe-row": {
    name: "swipe-row",
    description: "ردیف فهرست که با سوایپ اکشن‌ها را نشان می‌دهد و با سوایپ کامل حذف می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/swipe-row.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/swipe-row-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "swipe-row"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "swipeable-list": {
    name: "swipeable-list",
    description: "ردیف‌های سبک موبایل که با سوایپ چپ یا راست اکشن‌های زمینه‌ای را نشان می‌دهند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/swipeable-list.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/swipeable-list.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "swipeable-list"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "theme-toggle": {
    name: "theme-toggle",
    description: "سوئیچ فیزیکی با دستگیرهٔ نقطه‌دار. بزن و دکمه روی شیار فرو‌رفته حرکت می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/theme-toggle.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/theme-toggle-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "theme-toggle"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ticket-tear": {
    name: "ticket-tear",
    description: "نیمهٔ پایین بلیط را از پرفراژ به پایین بکش؛ جدا می‌شود و می‌افتد. با دکمه هم می‌توانی جدا کنی.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/ticket-tear.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/ticket-tear-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "ticket-tear"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "tactile-button": {
    name: "tactile-button",
    description: "راکر شیشه‌ای مایع که با فشار داخل چاهش کج می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/tactile-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/tactile-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "tactile-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "vertical-tabs": {
    name: "vertical-tabs",
    description: "تب عمودی با جابه‌جایی نرم محتوا.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/vertical-tabs.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/vertical-tabs-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "vertical-tabs"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "wake-slider": {
    name: "wake-slider",
    description: "اسلایدر بدون دسته از میله‌های باریک که سرعت کشیدن موجی پشت مقدار بلند می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/wake-slider.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/wake-slider-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "wake-slider"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "wheel-carousel": {
    name: "wheel-carousel",
    description: "چرخ نام‌ها کنار عکس بزرگ — بکشید، اسکرول کنید یا پیکان بزنید تا تصویر کراس‌فید شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/wheel-carousel.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/wheel-carousel.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "wheel-carousel"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }