/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "3d-book": {
    name: "3d-book",
    description: "یک کتاب سه‌بعدی تعاملی با انیمیشن ورق‌زدن صفحات.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/3d-book.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/3d-book.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "3d-book"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accessible-action": {
    name: "accessible-action",
    description: "پشتهٔ کارت قابل کشیدن با شیب سه‌بعدی، ژست ارسال به پشت، کلیک، چرخش تصادفی و فنر نرم.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/accessible-action.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/accessible-action-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "accessible-action"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordionos": {
    name: "accordionos",
    description: "آکاردئون شماره‌دار که با باز شدن هر ردیف تصویر بزرگ را عوض می‌کند، با پخش خودکار اختیاری.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/accordionos.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/accordionos.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "accordionos"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "analog-stick": {
    name: "analog-stick",
    description: "اهرم فلزی که با فشار کج می‌شود. روی یک ربع هاور کنید؛ کلاهک می‌لرزد، سایه جابه‌جا می‌شود و فلش همرنگ کهربایی می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/analog-stick.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/analog-stick-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "analog-stick"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-collection": {
    name: "animated-collection",
    description: "مجموعه‌ای از آثار که بین نمای فهرست، کارت و پشتهٔ فشرده مورف می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/animated-collection.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/animated-collection.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-collection"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-tabs": {
    name: "animated-tabs",
    description: "حرکت نرم نشانگر بین تب‌ها و انتقال انیمیشنی محتوای هر تب.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/animated-tabs.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/animated-tabs-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-tabs"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bento-card": {
    name: "bento-card",
    description: "یک کاشی شیشه‌ای با تب‌هایی که پیش‌نمای داشبورد را داخل همان کارت عوض می‌کنند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/bento-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/bento-card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "bento-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bottom-menu": {
    name: "bottom-menu",
    description: "داک فشرده‌ای که به جستجو، یادداشت، اعلان، پروفایل و تم باز می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/bottom-menu.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/bottom-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "bottom-menu"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bucket": {
    name: "bucket",
    description: "قیف شیشه‌ای که چیپ‌های قابلیت را یکی‌یکی مثل سینی گیراندازی پرتاب می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/bucket.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "hooks/use-mobile.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/bucket-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "bucket"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-folder": {
    name: "card-folder",
    description: "کارت پوشه‌ای متحرک با تصویر پس‌زمینه، شیء شناور، افکت هاور و رنگ و متن قابل تنظیم.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/card-folder.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/card-folder-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "card-folder"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "client-card": {
    name: "client-card",
    description: "کارت CRM مشتری با حلقه‌های پرداخت و مهلت، به‌علاوهٔ پشتهٔ آواتار مورف‌شونده.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/client-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/client-card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "client-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "confidential-folder": {
    name: "confidential-folder",
    description: "غلاف زغالی که نامه را بیرون می‌کشد، برمی‌گرداند و روبه‌روی شما می‌نشاند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/confidential-folder.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/confidential-folder.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "confidential-folder"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "corner-video": {
    name: "corner-video",
    description: "پخش‌کنندهٔ جمع‌وجور گوشه با مورف باز/بسته، پخش خودکار، بی‌صدا، بزرگ‌نمایی، کنترل هاور و اسکراب ویدیو.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/corner-video.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/corner-video-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "corner-video"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "coverflow-drag": {
    name: "coverflow-drag",
    description: "کاورفلوی افقی از پرتره‌ها که با کشیدن کوچک، کم‌نور و قفل می‌شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/coverflow-drag.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/coverflow-drag-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "coverflow-drag"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "create-menu": {
    name: "create-menu",
    description: "قرص «شروع ساخت» که با فنر به فهرست اکشن‌های ساخت باز می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/create-menu.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/create-menu-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "create-menu"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "curve-drawer": {
    name: "curve-drawer",
    description: "کشوهای کناری که لبهٔ داخلی‌شان با برآمدگی شروع می‌شود و با نشستن پنل صاف می‌شود.",
    type: "registry:component",
    registryDependencies: ["button"],
    files: [{
      path: "registry/default/example/curve-drawer.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/curve-drawer-primitives.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/curve-drawer-curve.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/curve-drawer-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "curve-drawer"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "day-picker": {
    name: "day-picker",
    description: "چیپ تکرار که به روزانه / هفتگی / ماهانه / سالانه باز می‌شود، بعد به روزهای هفته.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/day-picker.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/day-picker.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "day-picker"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "delete-button": {
    name: "delete-button",
    description: "دکمهٔ قرمز حذف که قبل از انجام کار به شمارش معکوس با امکان لغو تبدیل می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/delete-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/delete-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "delete-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dial-volume": {
    name: "dial-volume",
    description: "ولوم فلزی را بچرخان؛ حلقهٔ چراغ‌های مربعی سطح صدا را نشان می‌دهد و درصد به‌روز می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/dial-volume.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/dial-volume-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "dial-volume"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "discover-button": {
    name: "discover-button",
    description: "کنترل گرد جستجو که کنار تراشه‌های محبوب و علاقه‌مندی‌ها به فیلد کشیده می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/discover-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/discover-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "discover-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "discrete-tabs": {
    name: "discrete-tabs",
    description: "تب‌های آیکنی آرام که با برچسب باز می‌شوند و هنگام فعال شدن درخشش کوتاهی دارند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/discrete-tabs.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/discrete-tabs-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "discrete-tabs"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "drawer-buttons": {
    name: "drawer-buttons",
    description: "دو دکمه که کشوی کناری را با تا شدن سه‌بعدی باز می‌کنند. پرداخت از راست، سبد از چپ؛ فیلدها پشت‌سرهم ظاهر می‌شوند.",
    type: "registry:component",
    registryDependencies: ["button","input","textarea","select","field"],
    files: [{
      path: "registry/default/example/drawer-buttons.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/drawer-buttons-drawer.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/drawer-buttons-field.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/drawer-buttons-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "drawer-buttons"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dynamic-grid-gallery": {
    name: "dynamic-grid-gallery",
    description: "گرید عکسی ۳×۲ که ردیف و ستون هاور‌شده را بزرگ می‌کند تا یک قاب مرکز صحنه شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/dynamic-grid-gallery.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/dynamic-grid-gallery-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "dynamic-grid-gallery"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dynamic-toolbar": {
    name: "dynamic-toolbar",
    description: "نوار آیکنی که با ورق زدن بین ابزارهای اصلی و مجموعهٔ دوم، عرضش را عوض می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/dynamic-toolbar.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "hooks/use-measure.tsx",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/dynamic-toolbar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "dynamic-toolbar"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "editorial-deck": {
    name: "editorial-deck",
    description: "دستهٔ داستان تحریریه‌ای روی هم. کارت جلو را بکشید؛ با فنر به ته دسته برمی‌گردد.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/editorial-deck.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/editorial-deck-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "editorial-deck"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "empty-testimonial": {
    name: "empty-testimonial",
    description: "حالت خالی «دیوار محبت» — روی پوشه بزنید؛ سه برگه با فنر بیرون می‌آیند تا اولین نقل‌قول را اضافه کنید.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/empty-testimonial.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/empty-testimonial-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "empty-testimonial"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "event-countdown": {
    name: "event-countdown",
    description: "نشان می‌دهد چقدر تا شروع رویداد مانده — روز، ساعت، دقیقه و ثانیه.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/event-countdown.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/event-countdown-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "event-countdown"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "expandable-gallery": {
    name: "expandable-gallery",
    description: "گالری عکس با باز شدن نرم آیتم‌ها از پشته به شبکه.",
    type: "registry:component",
    registryDependencies: ["button"],
    files: [{
      path: "registry/default/example/expandable-gallery.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/expandable-gallery-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "expandable-gallery"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "feature-carousel": {
    name: "feature-carousel",
    description: "چیپ‌های شناور یک‌طرف، عکس بزرگ طرف دیگر — قابلیت را بزن، تصویر دنبال می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/feature-carousel.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/feature-carousel-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "feature-carousel"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "filter-interaction": {
    name: "filter-interaction",
    description: "فهرست فیلتر تعاملی با هاور، انتخاب و پنل تغییرشکل‌دهنده.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/filter-interaction.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/filter-interaction.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "filter-interaction"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "fluid-expanding-grid": {
    name: "fluid-expanding-grid",
    description: "شبکهٔ عکسی که با کلیک یکی ردیف را می‌گیرد و بقیه کنار می‌روند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/fluid-expanding-grid.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/fluid-expanding-grid.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "fluid-expanding-grid"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "focus-testimonials": {
    name: "focus-testimonials",
    description: "ردیف آواتار — روی یکی هاور کن تا نقل‌قول جلو بیاید و تولتیپ نام دنبال ماوس برود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/focus-testimonials.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/focus-testimonials.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "focus-testimonials"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "folder-interaction": {
    name: "folder-interaction",
    description: "پوشه‌ای که با کلیک باز می‌شود و برگه‌ها با فنر بیرون می‌آیند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/folder-interaction.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/folder-interaction.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "folder-interaction"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "get-in-touch": {
    name: "get-in-touch",
    description: "قرص براق تماس. هاور کنید تا برچسب برود، پرتره و «شما» یکی شوند، بعد «بزن حرف بزنیم!» نوشته شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/get-in-touch.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/get-in-touch-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/get-in-touch-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "get-in-touch"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "holographic-referral-card": {
    name: "holographic-referral-card",
    description: "کارت دعوت تیره که با اشاره‌گر سه‌بعدی کج می‌شود؛ درخشش هولوگرافیک دنبال می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/holographic-referral-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/holographic-referral-card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "holographic-referral-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "gooey-navbar": {
    name: "gooey-navbar",
    description: "ناوبری قرصی که با هاور به همسایه ذوب می‌شود — پل مایع و نقطهٔ فعال.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/gooey-navbar.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/gooey-navbar-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "gooey-navbar"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "infinite-grid": {
    name: "infinite-grid",
    description: "بوم محصول با حرکت آزاد که تا ابد کاشی می‌شود — بکشید، اسکرول کنید، ورق بزنید.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/infinite-grid.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/infinite-grid.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "infinite-grid"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "inline-edit": {
    name: "inline-edit",
    description: "ورودی که بین حالت خواندن و ویرایش جابه‌جا می‌شود.",
    type: "registry:component",
    registryDependencies: ["input"],
    files: [{
      path: "registry/default/example/inline-edit.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/inline-edit.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "inline-edit"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "liquid-index": {
    name: "liquid-index",
    description: "فهرست قابلیتی که نشان هاور آن گرادیان مایع WebGL است و ردیف را دنبال می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/liquid-index.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/liquid-index-canvas.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/liquid-index-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "liquid-index"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "luck-wheel": {
    name: "luck-wheel",
    description: "چرخ شانس کازینویی؛ سرعت را انتخاب کن، بچرخان، با شتاب و ترمز نرم روی جایزه می‌ایستد.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/luck-wheel.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/luck-wheel-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "luck-wheel"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "magnified-bento": {
    name: "magnified-bento",
    description: "کارت بنتو با لنز ذره‌بین قابل‌کشیدن روی چیپ‌های در حال اسکرول.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/magnified-bento.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/magnified-bento-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "magnified-bento"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "morphing-input": {
    name: "morphing-input",
    description: "فیلد ورودی که بین حالت‌های مختلف شکل عوض می‌کند.",
    type: "registry:component",
    registryDependencies: ["input"],
    files: [{
      path: "registry/default/example/morphing-input.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/morphing-input.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "morphing-input"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "nested-dropdown": {
    name: "nested-dropdown",
    description: "منوی کشویی انیمیشنی تو‌در‌تو با آیکون — دکمه به منو تبدیل می‌شود و زیرمنوها با حرکت نرم باز می‌شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/nested-dropdown.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/nested-dropdown-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "nested-dropdown"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "multi-step-form": {
    name: "multi-step-form",
    description: "فرم چندمرحله‌ای پویا و متحرک با اعتبارسنجی.",
    type: "registry:component",
    registryDependencies: ["card","button","input","textarea","select","badge","calendar","popover"],
    files: [{
      path: "registry/default/example/multi-step-form.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/multi-step-form.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "multi-step-form"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "overlapping-slider": {
    name: "overlapping-slider",
    description: "ردیف تمام‌عرض کارت‌های پرتره؛ با حرکت، کارت قبلی کوچک و عقب می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/overlapping-slider.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/overlapping-slider-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "overlapping-slider"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "otp-cascade": {
    name: "otp-cascade",
    description: "شش خانهٔ کد تأیید؛ رقم‌ها یکی‌یکی پر می‌شوند و با کد درست یا غلط بازخورد سبز یا قرمز می‌گیری.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/otp-cascade.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/otp-cascade-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "otp-cascade"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "perspective-text-scroll": {
    name: "perspective-text-scroll",
    description: "متنی که با اسکرول در پرسپکتیو می‌آید، می‌نشیند و دور می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/perspective-text-scroll.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/perspective-text-scroll-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "perspective-text-scroll"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "photo-albums": {
    name: "photo-albums",
    description: "پشته‌های کج آلبوم که به شبکهٔ عکس با المان مشترک باز می‌شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/photo-albums.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/photo-albums-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "photo-albums"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "paper-shred-button": {
    name: "paper-shred-button",
    description: "روی حذف هاور کنید تا صفحه ظاهر شود. کلیک کنید تا صفحه بریده شود و نوارهای کاغذ پایین کشیده شوند. بعد از چند ثانیه ریست می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/paper-shred-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/paper-shred-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "paper-shred-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "polaroid-drag": {
    name: "polaroid-drag",
    description: "چاپ‌های فوری که روی میز می‌کشید — با سرعت کج می‌شوند، روی هم می‌آیند و نوار چسب یا پونز می‌گیرند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/polaroid-drag.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/polaroid-drag.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "polaroid-drag"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "polaroid-stack": {
    name: "polaroid-stack",
    description: "هفت پولاروید روی هم. با هاور به قوسی از یک گوشه بادبزن می‌شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/polaroid-stack.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/polaroid-stack-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "polaroid-stack"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pop-tilt-cards": {
    name: "pop-tilt-cards",
    description: "دستهٔ پاستلی بادبزنی — روی یک کارت هاور کنید تا بالا بپرد و همسایه‌ها کج شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/pop-tilt-cards.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/pop-tilt-cards-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "pop-tilt-cards"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pricing-card": {
    name: "pricing-card",
    description: "انتخابگر باریک پلن با سوییچ ماهانه/سالانه، قیمت‌های غلتان و برچسب تخفیف.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/pricing-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/pricing-card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "pricing-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "prize-coins": {
    name: "prize-coins",
    description: "جعبه طلایی جایزه را باز کن؛ سکه‌ها پرواز می‌کنند و در شمارندهٔ گوشه جمع می‌شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/prize-coins.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/prize-coins-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "prize-coins"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "prompt-box": {
    name: "prompt-box",
    description: "کامپوزر چت جمع‌شده که به textarea با منوی مدل، کنترل ارسال و پیش‌نمایش هاور مدل انتخاب‌شده باز می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/prompt-box.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/prompt-box-icons.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/prompt-box-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "prompt-box"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "rolling-card-stack": {
    name: "rolling-card-stack",
    description: "پشتهٔ کارت غلتان واکنش‌گرا با سوایپ، کیبورد، پخش خودکار و محتوای قابل تنظیم.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/rolling-card-stack.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/rolling-card-stack.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "rolling-card-stack"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "save-button": {
    name: "save-button",
    description: "دکمه‌ای با وضعیت‌های متحرک برای آماده، در حال ذخیره و موفق.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/save-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/save-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "save-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scan-document": {
    name: "scan-document",
    description: "روی اسکن بزن؛ صفحه باز می‌شود، می‌چرخد و نوار نور آن را می‌خواند. بعد از انجام‌شدن ریست می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/scan-document.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/scan-document-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "scan-document"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scroll-split-cards": {
    name: "scroll-split-cards",
    description: "یک عکس که با اسکرول به سه پنل می‌شکند، بعد برمی‌گردد و متن نشان می‌دهد.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/scroll-split-cards.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/scroll-split-cards-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "scroll-split-cards"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scroll-stack-deck": {
    name: "scroll-stack-deck",
    description: "کارت‌های پروژهٔ وابسته به اسکرول که در ویوپورت پین می‌شوند و با پایین‌آمدن پشته، مقیاس و نشست پیدا می‌کنند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/scroll-stack-deck.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/scroll-stack-deck-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "scroll-stack-deck"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "set-timer": {
    name: "set-timer",
    description: "چرخ را بچرخان، شروع کن، بعد مکث یا لغو. یک سطح در هر مرحله شکل عوض می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/set-timer.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/set-timer-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "set-timer"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shake-testimonial-card": {
    name: "shake-testimonial-card",
    description: "کارت‌های نظر که می‌لرزند و بعد به پشت پشته پرتاب می‌شوند — پخش خودکار یا کلیک.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/shake-testimonial-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/shake-testimonial-card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "shake-testimonial-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "slide-subscribe": {
    name: "slide-subscribe",
    description: "دورهٔ صورتحساب را انتخاب کنید، بعد برای شروع آزمایش بکشید.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/slide-subscribe.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/slide-subscribe-unlock.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/default/example/slide-subscribe-shimmer.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/slide-subscribe-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "slide-subscribe"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "smooth-dropdown": {
    name: "smooth-dropdown",
    description: "دکمهٔ گردی که به منو تبدیل می‌شود — ردیف‌ها پلکانی می‌آیند، پوسته تغییر اندازه می‌دهد و با کلیک بیرون بسته می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/smooth-dropdown.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/smooth-dropdown.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "smooth-dropdown"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "stack-scroll-reveal": {
    name: "stack-scroll-reveal",
    description: "کارت‌های مطالعهٔ موردی وابسته به اسکرول که در ویوپورت پین می‌شوند و با پایین آمدن ورق می‌خورند، کوچک می‌شوند و محو می‌شوند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/stack-scroll-reveal.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/stack-scroll-reveal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "stack-scroll-reveal"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "stacked-list": {
    name: "stacked-list",
    description: "ویجت افراد — پشتهٔ کوتاه اعضا که به فهرست قابل جستجو تبدیل می‌شود.",
    type: "registry:component",
    registryDependencies: ["input","button"],
    files: [{
      path: "registry/default/example/stacked-list.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/stacked-list.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "stacked-list"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "stacked-outline-text": {
    name: "stacked-outline-text",
    description: "تایپ خط‌دار سنگین که می‌توانید بکشید. سرعت، رد سفید-روی-سیاه پشته‌ای می‌گذارد که با رها کردن برمی‌گردد.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/stacked-outline-text.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/stacked-outline-text-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "stacked-outline-text"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "stamp-approve": {
    name: "stamp-approve",
    description: "روی مهر تأیید بزن؛ مهر باد می‌گیرد، روی سند می‌خورد و اثر دایره‌ای «تأیید شد» دقیقاً همان‌جا می‌ماند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/stamp-approve.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/stamp-approve-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "stamp-approve"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "theme-toggle": {
    name: "theme-toggle",
    description: "سوئیچ فیزیکی با دستگیرهٔ نقطه‌دار. بزن و دکمه روی شیار فرو‌رفته حرکت می‌کند.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/theme-toggle.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/theme-toggle-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "theme-toggle"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ticket-tear": {
    name: "ticket-tear",
    description: "نیمهٔ پایین بلیط را از پرفراژ به پایین بکش؛ جدا می‌شود و می‌افتد. با دکمه هم می‌توانی جدا کنی.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/ticket-tear.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/ticket-tear-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "ticket-tear"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "tactile-button": {
    name: "tactile-button",
    description: "راکر شیشه‌ای مایع که با فشار داخل چاهش کج می‌شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/tactile-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/tactile-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "tactile-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "vertical-tabs": {
    name: "vertical-tabs",
    description: "تب عمودی با جابه‌جایی نرم محتوا.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/vertical-tabs.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/vertical-tabs-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "vertical-tabs"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "wheel-carousel": {
    name: "wheel-carousel",
    description: "چرخ نام‌ها کنار عکس بزرگ — بکشید، اسکرول کنید یا پیکان بزنید تا تصویر کراس‌فید شود.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/wheel-carousel.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/wheel-carousel.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "wheel-carousel"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }