/** Persian labels for browse/docs nav — primary over English titles. */
export const COMPONENT_TITLES_FA: Record<string, string> = {
  "3d-book": "کتاب سه‌بعدی",
  "accessible-action": "عملیات دسترس‌پذیر",
  accordionos: "آکاردئون",
  "analog-stick": "دسته آنالوگ",
  "animated-collection": "مجموعه متحرک",
  "animated-tabs": "تب‌های متحرک",
  "bento-card": "کارت بنتو",
  "bottom-menu": "منوی پایین",
  bucket: "باکت",
  "card-folder": "پوشه کارتی",
  "client-card": "کارت مشتری",
  "confidential-folder": "پوشه محرمانه",
  "corner-video": "ویدیوی گوشه",
  "coverflow-drag": "جابجایی کاورفلو",
  "create-menu": "منوی ایجاد",
  "curve-drawer": "کشوی منحنی",
  "day-picker": "انتخاب روز",
  "delete-button": "دکمه حذف",
  "dial-volume": "ولوم چرخشی",
  "discover-button": "دکمه کاوش",
  "discrete-tabs": "تب‌های تفکیک‌شده",
  "drawer-buttons": "دکمه‌های کشویی",
  "dynamic-grid-gallery": "گالری شبکه‌ای پویا",
  "dynamic-toolbar": "نوار ابزار پویا",
  "editorial-deck": "چیدمان تحریریه",
  "empty-testimonial": "بخش نظر خالی",
  "event-countdown": "شمارش معکوس رویداد",
  "expandable-gallery": "گالری بازشونده",
  "feature-carousel": "کاروسل امکانات",
  "fluid-expanding-grid": "شبکه بازشونده روان",
  "focus-testimonials": "نظرات متمرکز",
  "folder-interaction": "تعامل با پوشه",
  "get-in-touch": "تماس با ما",
  "gooey-navbar": "نوار پیمایش چسبان",
  "holographic-referral-card": "کارت دعوت هولوگرافیک",
  "infinite-grid": "بوم بی‌نهایت",
  "inline-edit": "ویرایش درجا",
  "liquid-index": "فهرست روان",
  "luck-wheel": "چرخ شانس",
  "filter-interaction": "آیتم فهرست",
  "magnified-bento": "بنتوی بزرگ‌نمایی‌شده",
  "morphing-input": "ورودی تغییرشکل‌دهنده",
  "nested-dropdown": "منوی کشویی تو‌در‌تو",
  "tooltip": "تولتیپ",
  "upload-dropzone": "دراپ‌زون آپلود",
  "typed-code": "کد تایپ‌شونده",
  "animated-switches": "سوئیچ‌های انیمیشنی",
  "multi-step-form": "فرم چندمرحله‌ای",
  "overlapping-slider": "اسلایدر هم‌پوشان",
  "otp-cascade": "کد تأیید آبشاری",
  "paper-shred-button": "دکمه کاغذخُردکن",
  "perspective-text-scroll": "اسکرول پرسپکتیو متن",
  "photo-albums": "آلبوم عکس",
  "polaroid-drag": "جابجایی پولاروید",
  "polaroid-stack": "چیدمان پولاروید",
  "pop-tilt-cards": "کارت‌های چرخان",
  "pricing-card": "کارت قیمت‌گذاری",
  "prize-coins": "سکه‌های جایزه",
  "prompt-box": "جعبه پرامپت",
  "rolling-card-stack": "پشته کارت چرخان",
  "scan-document": "اسکن سند",
  "scroll-split-cards": "کارت‌های جداشونده با اسکرول",
  "scroll-stack-deck": "چیدمان پشته‌ای اسکرول",
  "set-timer": "تنظیم زمان‌سنج",
  "shake-testimonial-card": "کارت نظر لرزان",
  "slide-subscribe": "اشتراک کشویی",
  "smooth-dropdown": "منوی بازشوی روان",
  "stack-scroll-reveal": "نمایش پشته‌ای هنگام اسکرول",
  "stacked-list": "فهرست پشته‌ای",
  "stacked-outline-text": "متن دورخطی پشته‌ای",
  "stamp-approve": "مهر تأیید",
  "ticket-tear": "بلیط پاره",
  "save-button": "دکمه وضعیت",
  "tactile-button": "دکمه تعاملی",
  "theme-toggle": "تغییر پوسته",
  "vertical-tabs": "تب‌های عمودی",
  "wheel-carousel": "کاروسل چرخ",
};

export function titleFaFor(slug: string): string | undefined {
  return COMPONENT_TITLES_FA[slug];
}
