/** Persian labels for browse/docs nav — primary over English titles. */
export const COMPONENT_TITLES_FA: Record<string, string> = {
  "3d-book": "کتاب سه‌بعدی",
  "accessible-action": "دکمه دسترس‌پذیر",
  accordionos: "آکاردئون",
  "analog-stick": "جوی‌استیک",
  "animated-bar-chart": "نمودار میله‌ای",
  "animated-donut-chart": "نمودار دونات",
  "animated-line-chart": "نمودار خطی",
  "animated-spark-chart": "نمودار روند کوچک",
  "command-palette": "پالت فرمان",
  "kanban-board": "برد کانبان",
  "animated-collection": "مجموعه متحرک",
  "animate-tabs": "تب‌های انیمیت",
  "animated-tabs": "تب‌های متحرک",
  "bento-card": "کارت بنتو",
  "bloom-menu": "منوی شکوفایی",
  "bounce-cards": "کارت‌های بانس",
  "bottom-menu": "منوی پایین",
  bucket: "سطل",
  "card-folder": "پوشه کارت",
  "client-card": "کارت مشتری",
  "confidential-folder": "پوشه محرمانه",
  "corner-video": "ویدیوی شناور",
  "coverflow-drag": "کاورفلو سه‌بعدی",
  "create-menu": "منوی ایجاد",
  "curve-drawer": "کشوی منحنی",
  "date-field": "فیلد تاریخ",
  "jalali-wheel-picker": "چرخان تاریخ شمسی",
  "peek-rating": "پیش‌نمایش امتیاز",
  "pulse-heart": "قلب تپنده",
  "number-ticker": "شمارنده عددی",
  "voice-orb": "گوی صوتی",
  "team-carousel": "کاروسل تیم",
  "approval-card": "کارت تأیید",
  "image-generation": "تولید تصویر",
  "morphing-tabs": "تب‌های تغییرشکل‌دهنده",
  "signup-form": "فرم ثبت‌نام",
  "day-picker": "انتخاب روز",
  "delete-button": "دکمه حذف",
  "dial-volume": "ولوم چرخشی",
  "discover-button": "دکمه اکتشاف",
  "discrete-tabs": "تب‌های مجزا",
  "drawer-buttons": "دکمه‌های Drawer",
  "dynamic-grid-gallery": "گالری شبکه‌ای پویا",
  "dynamic-toolbar": "نوار ابزار پویا",
  "editorial-deck": "چیدمان مجله‌ای",
  "empty-testimonial": "حالت خالی نظرات",
  "event-countdown": "شمارش معکوس رویداد",
  "expandable-action-bar": "نوار اکشن بازشونده",
  "expandable-gallery": "گالری بازشونده",
  "feature-carousel": "کاروسل امکانات",
  "fluid-expanding-grid": "شبکه گسترش‌پذیر",
  "focus-testimonials": "نظرات برجسته",
  "folder-interaction": "تعامل با پوشه",
  "get-in-touch": "تماس با ما",
  "glide-select": "انتخاب لغزنده",
  "gooey-navbar": "نوار پیمایش ژله‌ای",
  "holographic-referral-card": "کارت دعوت هولوگرافیک",
  "infinite-grid": "بوم بی‌نهایت",
  "infinite-masonry": "شبکه نامنظم بی‌نهایت",
  "inline-edit": "ویرایش درجا",
  lanyard: "بند شناسایی",
  "lanyard-badge": "بند شناسایی بج",
  "liquid-index": "فهرست روان",
  "loading-states": "حالت‌های بارگذاری ایجنت",
  "luck-wheel": "چرخ شانس",
  "file-upload-progress": "پیشرفت آپلود",
  "filter-interaction": "آیتم فهرست",
  "magnified-bento": "بنتوی بزرگ‌نمایی",
  "morphing-input": "ورودی تغییرشکل‌دهنده",
  "nested-dropdown": "منوی کشویی تو‌در‌تو",
  "toast-stack": "پشته اعلان",
  "todo-list": "فهرست کارها",
  "tooltip": "راهنمای شناور",
  "undo-delete": "حذف با بازگردانی",
  "upload-dropzone": "دراپ‌زون آپلود",
  "typed-code": "کد تایپ‌شونده",
  "animated-switches": "سوئیچ‌های انیمیشنی",
  "animated-checkboxes": "چک‌باکس‌های انیمیشنی",
  "animated-select": "انتخاب‌گر متحرک",
  "sortable-list": "لیست مرتب‌سازی",
  "swipe-row": "ردیف سوایپ",
  "swipeable-list": "لیست سوایپ‌پذیر",
  "wake-slider": "اسلایدر موج",
  "animated-data-table": "جدول داده انیمیشنی",
  "animated-sidebars": "سایدبار متحرک",
  "horizontal-menu": "منوی افقی",
  "expandable-card": "کارت گسترش‌پذیر",
  "multi-step-form": "فرم چندمرحله‌ای",
  "overlapping-slider": "اسلایدر هم‌پوشان",
  "otp-cascade": "کد تأیید مرحله‌ای",
  "paper-shred-button": "دکمه خردکننده کاغذ",
  "perspective-text-scroll": "اسکرول سه‌بعدی متن",
  "photo-albums": "آلبوم عکس",
  "polaroid-drag": "جابه‌جایی پولاروید",
  "polaroid-stack": "چیدمان پولاروید",
  "pop-tilt-cards": "کارت‌های سه‌بعدی",
  "pricing-card": "کارت قیمت‌گذاری",
  "profile-card": "کارت پروفایل",
  "prize-coins": "سکه‌های جایزه",
  "prompt-box": "جعبه پرامپت",
  "rolling-card-stack": "پشته کارت متحرک",
  "scan-document": "اسکن سند",
  "scroll-split-cards": "کارت‌های تفکیک‌شونده",
  "scroll-stack-deck": "کارت‌های پشته‌ای",
  "set-timer": "تنظیم زمان‌سنج",
  "shake-testimonial-card": "کارت نظر لرزان",
  "slide-subscribe": "فرم اشتراک",
  "slosh-gauge": "گیج مایع",
  "smooth-dropdown": "منوی بازشوی روان",
  "spotlight-card": "کارت نورپردازی",
  "stack-scroll-reveal": "نمایش لایه‌ای اسکرول",
  "stacked-list": "فهرست لایه‌ای",
  "stacked-outline-text": "متن دورخطی پشته‌ای",
  "stamp-approve": "مهر تأیید",
  "status-mark": "نشان وضعیت",
  "comet-dial": "صفحهٔ دنباله‌دار",
  "ticket-tear": "بلیت پاره‌شونده",
  "save-button": "دکمه وضعیت",
  "tactile-button": "دکمه تعاملی",
  "theme-toggle": "تغییر پوسته",
  "vertical-tabs": "تب‌های عمودی",
  "wheel-carousel": "کاروسل چرخ",
};

export function titleFaFor(slug: string): string | undefined {
  return COMPONENT_TITLES_FA[slug];
}
