/** Persian labels for browse/docs nav — English title stays primary. */
export const COMPONENT_TITLES_FA: Record<string, string> = {
  "3d-book": "کتاب سه‌بعدی",
  "animated-collection": "مجموعه متحرک",
  "bottom-menu": "منوی پایین",
  "day-picker": "انتخاب روز",
  "delete-button": "دکمه حذف",
  "discover-button": "دکمه کشف",
  "discrete-tabs": "تب‌های گسسته",
  "dynamic-toolbar": "نوار ابزار پویا",
  "expandable-gallery": "گالری بازشو",
  "feature-carousel": "کاروسل ویژگی",
  "folder-interaction": "تعامل پوشه",
  "inline-edit": "ویرایش درجا",
  "filter-interaction": "آیتم لیست",
  "morphing-input": "ورودی شکل‌پذیر",
  "multi-step-form": "فرم چندمرحله‌ای",
  "pricing-card": "کارت قیمت",
  "shake-testimonial-card": "نظر لرزان",
  "smooth-dropdown": "منوی بازشو نرم",
  "save-button": "دکمه وضعیت",
  "vertical-tabs": "تب‌های عمودی",
  "stacked-list": "لیست پشته‌ای",
  bucket: "سطل",
  "fluid-expanding-grid": "شبکه شناور",
  "bento-card": "کارت بنتو",
  "magnified-bento": "بنتو ذره‌بین",
  "editorial-deck": "دسته سرمقاله",
  "empty-testimonial": "نظر خالی",
  "accessible-action": "اکشن دسترس‌پذیر",
  accordionos: "آکاردئون‌اواس",
  "card-folder": "پوشه کارتی",
  "confidential-folder": "پوشه محرمانه",
  "corner-video": "ویدیوی گوشه",
  "focus-testimonials": "نظرات متمرکز",
  "infinite-grid": "بوم بی‌نهایت",
  "polaroid-drag": "درگ پولاروید",
  "pop-tilt-cards": "کارت‌های کج‌شونده",
  "rolling-card-stack": "پشته غلتان",
  "scroll-stack-deck": "دسته اسکرول",
  "stack-scroll-reveal": "آشکارسازی پشته",
  "perspective-text-scroll": "متن پرسپکتیو",
  "wheel-carousel": "کاروسل چرخ",
  "client-card": "کارت مشتری",
  "coverflow-drag": "درگ کاورفلوی",
  "overlapping-slider": "اسلایدر هم‌پوشان",
  "tactile-button": "دکمه لمسی",
  "gooey-navbar": "نوار چسبناک",
  "dynamic-grid-gallery": "گالری شبکه پویا",
  "scroll-split-cards": "کارت‌های شکافته",
  "create-menu": "منوی ساخت",
  "liquid-index": "فهرست مایع",
  "photo-albums": "آلبوم عکس",
  "slide-subscribe": "اشتراک اسلایدی",
  "set-timer": "تنظیم تایمر",
  "stacked-outline-text": "متن دورخط پشته‌ای",
  "drawer-buttons": "دکمه‌های کشو",
  "prompt-box": "جعبه پرامپت",
  "get-in-touch": "تماس بگیرید",
  "theme-toggle": "تغییر تم",
  "scan-document": "اسکن سند",
  "polaroid-stack": "پشته پولاروید",
  "analog-stick": "آنالوگ استیک",
  "paper-shred-button": "دکمه خردکن",
  "holographic-referral-card": "کارت دعوت هولوگرافیک",
  "curve-drawer": "کشوی منحنی",
};

export function titleFaFor(slug: string): string | undefined {
  return COMPONENT_TITLES_FA[slug];
}
